### ISSUE TITLE
query and queryman return different results for the same gene

### ISSUE THREAD

**Issue by YubinXie** [biothings/mygene.py#12]
Thanks for your package. It is nice!

I am trying to convert mice gene to the human gene name but somehow with the same gene name returns two different results by using query and query many functions.
![7679C20D-2A79-418C-9E3C-DF09D7C8735F](https://user-images.githubusercontent.com/16257776/92191067-bb833300-ee30-11ea-9ff5-bbb82363d48a.png)

**Comment by newgene** [comment]
@YubinXie `mg.query` and `mg.querymany` have slightly different query syntax for their different use cases. 

`mg.query` supports more[ flexible query syntax](https://docs.mygene.info/en/latest/doc/query_service.html#query-syntax) for a single query. `scope` parameter has no effect on `mg.query`. When 'Tmem27' is passed without a field prefix, it searches against a set of default fields, including the `alias` field, which is why it returns the match.

`mg.querymany` is more suitable for id-mapping and support a list of input terms for the batch query. [`scopes` parameter](https://docs.mygene.info/en/latest/doc/query_service.html#scopes) is used to specify the possible fields to find the matching gene for each term.

Below are a few query examples to return consistent results using `mg.query` and `mg.querymany`
```
In [38]: mg.query('symbol:Tmem27', species='human')
Out[38]: {'took': 0, 'total': 0, 'max_score': None, 'hits': []}

In [39]: mg.query('symbol:Tmem27 OR alias:Tmem27', species='human')
Out[39]:
{'took': 9,
 'total': 1,
 'max_score': 15.878075,
 'hits': [{'_id': '57393',
   '_score': 15.878075,
   'entrezgene': '57393',
   'name': 'collectrin, amino acid transport regulator',
   'symbol': 'CLTRN',
   'taxid': 9606}]}

In [40]: mg.querymany('Tmem27', scopes='symbol', species='human')
querying 1-1...done.
Finished.
1 input query terms found no hit:
        ['Tmem27']
Pass "returnall=True" to return complete lists of duplicate or missing query terms.
Out[40]: [{'query': 'Tmem27', 'notfound': True}]

In [41]: mg.querymany('Tmem27', scopes='symbol,alias', species='human')
querying 1-1...done.
Finished.
Out[41]:
[{'query': 'Tmem27',
  '_id': '57393',
  '_score': 15.879101,
  'entrezgene': '57393',
  'name': 'collectrin, amino acid transport regulator',
  'symbol': 'CLTRN',
  'taxid': 9606}]
```
