### ISSUE TITLE
querymany finds wrong genes due to overlapping symbols

### ISSUE THREAD

**Issue by Solatar** [biothings/mygene.py#13]
When I compared the querymany function in both python and R to the R functions mapIds (AnnotationDbi package) and alias2Symbol (limma package), both give the same results, but querymany seems to be different. I think this is because of genes with a symbol that is the very same as the alias of a different gene.
For example when querying the gene TYMP, querymany returned SCO2. TYMP used to be an alias for SCO2 so querymany converts TYMP to SCO2, while mapIds and alis2Symbol do not (they just return TYMP). Is there any way in querymany to turn this behaviour off, so when I have a list of genes I can just run 
`mg.querymany(genelist, scopes=["symbol","alias"], species="human")`
without having to worry about false genes coming up?

**Comment by newgene** [comment]
@Solatar gene SCO2 (GeneID: 9997) does include an alias of "TYMP", which is why it returns as a match:

https://www.ncbi.nlm.nih.gov/gene/9997 ("Also known as" section is corresponding to the "alias" field returned from MyGene.info API)

![image](https://user-images.githubusercontent.com/130158/94033633-03cdab00-fd76-11ea-8b97-6de0a3daa28a.png)

From MyGene.info API:
http://mygene.info/v3/gene/9997?fields=name,symbol,entrezgene,alias

If you don't want the matches from the `alias` field, you can remove it from the `scopes` parameter, or you can process the query results and pick the one you like (in the case multiple hits from symbol and alias matches).

Not sure why mapIds and alis2Symbol return differently, could be their data source is different or not up-to-date with NCBI. MyGene.info API was kept up-to-date with NCBI and other sources on the weekly base.

**Comment by Solatar** [comment]
yes, TYMP is listed as an alias of the SCO2 gene. What I meant though is that there also exists a different gene with the symbol TYMP (entrez ID: 1890). This is maybe why  the other packages don't translate it to SCO2. So whether or not to translate TYMP to SCO2 or to leave it as TYMP depends on the gene list (probably on how old it is).
That's what I meant with "wrong gene"; if you have a gene list that includes the gene TYMP (1890) and one runs this list through their standard pipeline to translate all symbols to e.g. entrez IDs, and part of that standard pipeline is to use querymany to convert old symbols to new ones, then one will end up with wrong genes (in this case SCO2). On the other hand, using e.g. mapIds could potentially miss some translations when processing a very old list (where SCO2 is listed as TYMP) which also results in a wrong gene.
If there would be a way to turn on/off the behaviour of translating aliases even if there is already a gene with the very symbol listed, users could adopt the function to the gene list they have. Of course one can also do this manually by first checking which symbols don't yield a result when queried only with the 'symbol' scope, and then query those with the 'alias' scope.

I just wanted to bring this up, because if I hadn't checked with the other packages I would have wrongfully included some genes into my list and I feel like this could easily happen to many people.

**Comment by newgene** [comment]
@Solatar yes, I understand your particular use case. There is a `size` parameter to the `querymany` should achieve what you want:

`size=1` basically tells our API return only the top hit for each input query term. Since the symbol match will always returns ahead of the alias match, you are safe to get back the matching one either symbol match or alias match when no symbol match.

```
In [5]: mg.querymany(['Tmem27', 'TYMP'], scopes='symbol,alias', species='human', size=1)
querying 1-2...done.
Finished.
Out[5]:
[{'query': 'Tmem27',
  '_id': '57393',
  '_score': 15.878911,
  'entrezgene': '57393',
  'name': 'collectrin, amino acid transport regulator',
  'symbol': 'CLTRN',
  'taxid': 9606},
 {'query': 'TYMP',
  '_id': '1890',
  '_score': 90.0078,
  'entrezgene': '1890',
  'name': 'thymidine phosphorylase',
  'symbol': 'TYMP',
  'taxid': 9606}]

# comparing to this query without size=1

In [6]: mg.querymany(['Tmem27', 'TYMP'], scopes='symbol,alias', species='human')
querying 1-2...done.
Finished.
1 input query terms found dup hits:
        [('TYMP', 2)]
Pass "returnall=True" to return complete lists of duplicate or missing query terms.
Out[6]:
[{'query': 'Tmem27',
  '_id': '57393',
  '_score': 15.879101,
  'entrezgene': '57393',
  'name': 'collectrin, amino acid transport regulator',
  'symbol': 'CLTRN',
  'taxid': 9606},
 {'query': 'TYMP',
  '_id': '1890',
  '_score': 90.007835,
  'entrezgene': '1890',
  'name': 'thymidine phosphorylase',
  'symbol': 'TYMP',
  'taxid': 9606},
 {'query': 'TYMP',
  '_id': '9997',
  '_score': 19.338736,
  'entrezgene': '9997',
  'name': 'synthesis of cytochrome C oxidase 2',
  'symbol': 'SCO2',
  'taxid': 9606}]
```

**Comment by newgene** [comment]
Assuming this issue is resolved now, close it now, but feel free to reopen it if you have further questions. @Solatar
