### ISSUE TITLE
query and querymany in disagreement

### ISSUE THREAD

**Issue by sjroth** [biothings/mygene.py#25]
![Screenshot 2024-10-29 at 4 36 28 PM](https://github.com/user-attachments/assets/5ff70a8b-0910-474b-86bf-776900db6843)
Please advise.

**Comment by newgene** [comment]
@sjroth thanks for reporting this to us. 

I had a quick check. On the surface, looks like it's due to that the matching `uniprot` field is empty for the gene of `80167`:

https://mygene.info/v3/gene/80167?fields=uniprot (returns empty, compared to what's returned from another gene, e.g. if replace the gene id with `1017`)

The first one using `mg.query` returns a hit because it searches for multiple default fields for the match gene, even though the `uniprot` is missing, there is a `accession.protein` field containing `Q0P651`):

https://mygene.info/v3/gene/80167?fields=accession.protein

The `scopes` parameter is not a valid parameter for `mg.query`, so it's get ignored (yes, ideally, it would be better to print out a warning that `scopes` is skipped).

In the 2nd `mg.querymany` query, the `scopes` parameter is valid, and it restricts the query only on the `uniprot` field. Because it's missing for this gene record, it then returns the empty hit as expected.

The equivalent code to do the same query using `mg.query` would be like this:

```
mg.query("uniprot:P24941", fields="entregene", species="human")
```
this will also restrict the query against the `uniprot` field only and returns empty hit as well.

**Comment by newgene** [comment]
As the next step, we will double check why this gene record of `80167` is missing a `uniprot` field. Whether this is due to the upstream data from the UniProt source, or an issue during our data processing. Will update here once we discovered something.

**Comment by jal347** [comment]
For our uniprot mapping, we use the current release of the ftp uniprot file [idmapping_selected.tab.gz](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/idmapping_selected.tab.gz). Using this file we can map all of the uniprot data onto the Entrezgene ID. I noticed that in their file they happen to be missing the data to map to gene id 80167. If you download the file and run `zcat idmapping_selected.tab.gz | awk -F'\t' '$3 == 80167'` there is no resulting output. Without the entrez id we cannot process our data to add the uniprot field to our gene record of 80167. 

This is a link to the readme for more context on how they map the ids to the file. 
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/README

I have also emailed Uniprot asking about this issue. 

Let me know if you have any other questions.

**Comment by jal347** [comment]
https://www.uniprot.org/uniprotkb/Q0P651/entry
https://www.uniprot.org/uniprotkb/P24941/entry

If we compare these two entries, under the Genome annotation databases section we can see that P24941 has the correct geneid data 1017 but the Q0P651 is missing the Geneid field.
