### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by sdhutchins** [biothings/mygene.py#5]
I'd really like to contribute to this project if possible.

1. I'd like to add a function that parses the df/dataframe output. When I first got started with this wrapper/package, it was a bit difficult to figure out what pandas functions to use.

2. Have you all considered continuous integration with travis.ci?

**Comment by newgene** [comment]
@sdhutchins Really appreciate you are willing to contribute. I want to point out that we are now moving to a universal Python client for all of our [BioThings APIs](http://biothings.io), including [MyGene.info](http://mygene.info) API:

https://pypi.org/project/biothings-client/   (code repo: [biothings/biothings_client.py](https://github.com/biothings/biothings_client.py))

With new "biothings_client", users just need to initialize as:

    from biothings_client import get_client
    mg = get_client('gene')

This is the same as this with "[mygene.py](https://pypi.org/project/mygene/)" module:

    import mygene
    mg = mygene.MyGeneInfo()

The rest should be exactly the same.

We would like to direct any new code development into that [new repo](https://github.com/biothings/biothings_client.py), and recommend our users to use "biothings_client" instead. But "[mygene.py](https://pypi.org/project/mygene/)" will still be maintained, so that the existing code won't break.


Nevertheless, two features you mentioned above would apply to "biothings_client" as well. Here are my comments:

1. I would like to know more about what you propose. Can you please give an example?

2. Yes, we did have a travis.ci account setup, will add travis-ci to "biothings_client" repo very soon.

**Comment by newgene** [comment]
@sdhutchins Also I don't want you feel that we don't welcome you to contribute to our "mygene.py" repo. If you feel more comfortable to work on our "mygene.py" repo, feel free to send us a pullrequest on this "mygene.py" repo, we can always move it to "biothings_client.py" repo later. if you prefer, you can send a pullrequest to "biothings_client.py" repo directly. Either way is fine :-)

**Comment by sdhutchins** [comment]
@newgene Thanks for such a timely response and for directing me to the biothings client! I'll be glad to implement it into what I do.


As for **1.**, I'm not sure if this is in the documentation but the api doesn't allow lowercase accessions (which isn't an issue with the API in my opinion) and for some users, this may throw them off (especially me at the beginning of my programming journey). I think including a function that makes the qterms upper case would be beneficial. 

Also, the `querymany` results returns as a dictionary or json type output which is fine as well, but for simplification, I think it could be a good idea to implement pandas with the `as_dataframe` option and do some "pre-cleaning" of the object/results returned in the querymany method.  

For example,

```python
# -*- coding: utf-8 -*-
from biothings_client import get_client
import pandas as pd

mg = get_client('gene')

accessions_list = [
    'nm_000250.1',
    'nm_006705.3',
    'nm_000250.1',
    'nm_015192.3',
    'nm_001243718.1',
    'nm_003404.4',
    'nm_001198713.1',
    'nm_001256213.1',
    'nm_181711.3',
    'nm_052876.3',
    'nm_004291.3',
    'nm_001164410.2',
    'nm_001267843.1',
    'nm_001834.3',
    'nm_000796.5',
    'nm_000817.2',
    'nm_002067.4',
    'nm_002072.4',
    'nm_175611.2',
    'nm_001301030.1',
    'nm_000832.6',
    'nm_000842.4',
    'nm_004839.3',
    'nm_006084.4',
    'nm_002229.2'
    ]

# Makes nm uppercase
accessions_list = [accession.upper() for accession in accessions_list]

query_many_results = mg.querymany(qterms=accessions_list, scopes='refseq',
                                 fields='symbol,name,entrezgene,summary',
                                 species='human', returnall=True, as_dataframe=True,
                                 size=1, verbose=True)


# Converts index of 'out' df to a column
query_many_results['out'].reset_index(level=0, inplace=True)

output = query_many_results['out']

# Turns dictionary of duplicates to a dataframe and adds column names
duplicates = pd.DataFrame.from_dict(query_many_results['dup'])
duplicates.columns = ['query', 'number of duplicates']

missing = query_many_results['missing']
```
That example should be reproducible.  Let me know your thoughts. Some of this is just to simplify the output, but if someone understands the pandas package, this maneuvering shouldn't be too hard. I find most people don't. At worst, I could provide this as an example for people in the documentation and that may be more appropriate than touching the code.

**Comment by newgene** [comment]
@sdhutchins that lowercase issue is definitely a bug on our end. We have now identified the issue, will deploy the fix soon (likely next week when we make a new data release). Thanks for letting us know.

Regarding the Pandas DataFrame output, the current code use either ```pandas.io.json.json_normalize``` or ```DataFrame.from_dict``` for the conversion:

https://github.com/biothings/biothings_client.py/blob/master/biothings_client/base.py#L124

Is the type of DataFrame you have (after ```reset_index(level=0, inplace=True)```) often more preferable? Any particular benefit one v.s. another in your particular case? 

And for "duplicates" and "missing", I agree with you, when ```as_dataframe=True```, it makes sense to have them output as a DataFrame as well.

**Comment by sdhutchins** [comment]
It's not critical to reset the index. It's just a bit easier to see the dataframe and have the queries as a column for further or down the line parsing by column. The biggest thing is having duplicates and missing as dataframes.

**Comment by newgene** [comment]
@sdhutchins got it, thanks. You are welcome to add this feature to "[biothings_client.py](https://github.com/biothings/biothings_client.py)" repo and send us a pull request.

I'm cc'ing @cyrus0824 from our dev team as well, and he can help answer any question if you have.

And also FYI, the lowercase issue has been fixed in a recent release of MyGene.info API. Thanks for reporting this to us.

**Comment by sdhutchins** [comment]
Thanks for all your help and answering the questions.

**Comment by sdhutchins** [comment]
Not sure if I ever mentioned but I added that to this PR https://github.com/biothings/biothings_client.py/pull/1
